/**
 * @file colony.ts
 * Anchor `Program` wrapper for the Hivemind on-chain program.
 * Provides typed, high-level methods for every program instruction.
 */

import { Connection, Keypair, PublicKey, SystemProgram } from "@solana/web3.js";
import * as anchor from "@coral-xyz/anchor";
import { Program, AnchorProvider } from "@coral-xyz/anchor";
import BN from "bn.js";
import * as crypto from "crypto";
import { WalletManager } from "./wallet.js";
import { SolanaRPC } from "./services/rpc.js";
import chalk from "chalk";
// IDL is generated by `anchor build` and placed in target/idl/hivemind.json
// The path is relative from the project root — adjust if running from agents/.
import type { Idl } from "@coral-xyz/anchor";
import type { Hivemind } from "../../target/idl/hivemind";

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

/** On-chain representation of the colony singleton. */
export interface ColonyState {
  authority: PublicKey;
  agentCount: number;
  treasury: PublicKey;
  totalTransactions: BN;
  bump: number;
}

/** On-chain representation of an individual agent. */
export interface AgentState {
  colony: PublicKey;
  agentIndex: number;
  role: Record<string, object>;
  vault: PublicKey;
  reputation: BN;
  dailyLimit: BN;
  perTxLimit: BN;
  dailySpent: BN;
  lastReset: BN;
  isFrozen: boolean;
  totalTasks: BN;
  successfulTasks: BN;
  bump: number;
}

/** Numeric role identifiers matching the Rust `AgentRole` enum order. */
export const AgentRole = {
  Scout: { scout: {} },
  Analyst: { analyst: {} },
  Executor: { executor: {} },
  Ledger: { ledger: {} },
} as const;

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/** Returns the current wall-clock time formatted as `HH:MM:SS`. */
function timestamp(): string {
  return new Date().toLocaleTimeString("en-US", { hour12: false });
}

/**
 * Converts a UTF-8 task description string to a 32-byte SHA-256 hash buffer.
 *
 * @param taskId - Human-readable task description.
 * @returns Byte array suitable for the `task_id` instruction parameter.
 */
function taskIdToBytes(taskId: string): number[] {
  return Array.from(
    crypto.createHash("sha256").update(taskId, "utf8").digest(),
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// ColonyClient
// ─────────────────────────────────────────────────────────────────────────────

/**
 * High-level client for the Hivemind Anchor program.
 *
 * Wraps every on-chain instruction in a typed async method that handles
 * PDA derivation, transaction sending, and error logging automatically.
 */
export class ColonyClient {
  private readonly program: Program<Hivemind>;
  private readonly wallet: Keypair;
  private readonly walletManager: WalletManager;
  private readonly connection: Connection;
  public readonly programId: PublicKey;

  /**
   * Creates a `ColonyClient` instance.
   *
   * @param wallet    - Authority keypair used to sign transactions.
   * @param programId - Deployed Hivemind program address.
   * @param idl       - The program IDL (loaded from `target/idl/hivemind.json`).
   */
  constructor(wallet: Keypair, programId: PublicKey, idl: Idl) {
    this.wallet = wallet;
    this.programId = programId;
    this.walletManager = new WalletManager();
    this.connection = SolanaRPC.getInstance().connection;

    const provider = new AnchorProvider(
      this.connection,
      new anchor.Wallet(wallet),
      { skipPreflight: false, commitment: "confirmed" },
    );
    anchor.setProvider(provider);

    this.program = new Program<Hivemind>(idl, provider);
    console.log(
      chalk.gray(
        `[COLONY][${timestamp()}] ColonyClient initialised. Program: ${programId.toBase58()}`,
      ),
    );
  }

  // ───────────────────────────────────────────────────────────────────────────
  // PDA helpers (private)
  // ───────────────────────────────────────────────────────────────────────────

  private getColonyPDA(): [PublicKey, number] {
    return this.walletManager.deriveColonyPDA(this.programId);
  }

  private getTreasuryPDA(colonyPubkey: PublicKey): [PublicKey, number] {
    return this.walletManager.deriveTreasuryPDA(colonyPubkey, this.programId);
  }

  private getAgentPDA(
    colonyPubkey: PublicKey,
    agentIndex: number,
  ): [PublicKey, number] {
    return this.walletManager.deriveAgentPDA(
      colonyPubkey,
      agentIndex,
      this.programId,
    );
  }

  private getVaultPDA(agentStatePubkey: PublicKey): [PublicKey, number] {
    return this.walletManager.deriveVaultPDA(agentStatePubkey, this.programId);
  }

  // ───────────────────────────────────────────────────────────────────────────
  // Instructions
  // ───────────────────────────────────────────────────────────────────────────

  /**
   * Calls the `initialize_colony` instruction to create the colony singleton
   * and seed the treasury with 1 SOL.
   *
   * @returns Transaction signature.
   * @throws `Error` if the transaction fails.
   */
  async initializeColony(): Promise<string> {
    try {
      const [colonyPDA] = this.getColonyPDA();
      const [treasuryPDA] = this.getTreasuryPDA(colonyPDA);

      const sig = await this.program.methods
        .initializeColony()
        .accounts({
          authority: this.wallet.publicKey,
          colony: colonyPDA,
          treasury: treasuryPDA,
          systemProgram: SystemProgram.programId,
        })
        .signers([this.wallet])
        .rpc({ skipPreflight: false, commitment: "confirmed" });

      console.log(
        chalk.green(`[COLONY][${timestamp()}] initializeColony tx: ${sig}`),
      );
      return sig;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      throw new Error(`[ColonyClient.initializeColony] Failed: ${msg}`);
    }
  }

  /**
   * Registers a new agent by calling the `register_agent` instruction.
   *
   * @param role        - Agent role object (use `AgentRole.Scout`, etc.).
   * @param dailyLimit  - Max lamports per 24-hour window.
   * @param perTxLimit  - Max lamports per single transaction.
   * @returns Transaction signature.
   * @throws `Error` if the transaction fails.
   */
  async registerAgent(
    role: Record<string, object>,
    dailyLimit: number,
    perTxLimit: number,
  ): Promise<string> {
    try {
      const [colonyPDA] = this.getColonyPDA();
      const [treasuryPDA] = this.getTreasuryPDA(colonyPDA);

      // Fetch current colony state to know the next agent index.
      const colony = (await this.program.account["colonyState"].fetch(
        colonyPDA,
      )) as ColonyState;
      const agentIndex = colony.agentCount;

      const [agentStatePDA] = this.getAgentPDA(colonyPDA, agentIndex);
      const [vaultPDA] = this.getVaultPDA(agentStatePDA);

      const sig = await this.program.methods
        .registerAgent(role, new BN(dailyLimit), new BN(perTxLimit))
        .accounts({
          authority: this.wallet.publicKey,
          colony: colonyPDA,
          treasury: treasuryPDA,
          agentState: agentStatePDA,
          vault: vaultPDA,
          systemProgram: SystemProgram.programId,
        })
        .signers([this.wallet])
        .rpc({ skipPreflight: false, commitment: "confirmed" });

      console.log(
        chalk.green(
          `[COLONY][${timestamp()}] registerAgent index=${agentIndex} role=${JSON.stringify(role)} tx: ${sig}`,
        ),
      );
      return sig;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      throw new Error(`[ColonyClient.registerAgent] Failed: ${msg}`);
    }
  }

  /**
   * Executes an agent-to-agent payment via the `agent_pay` instruction.
   *
   * @param fromAgentIndex - Zero-based index of the paying agent.
   * @param toAgentIndex   - Zero-based index of the receiving agent.
   * @param amount         - Lamports to transfer.
   * @param taskId         - Human-readable task description (hashed to 32 bytes internally).
   * @returns Transaction signature.
   * @throws `Error` if the transaction fails.
   */
  async agentPay(
    fromAgentIndex: number,
    toAgentIndex: number,
    amount: number,
    taskId: string,
  ): Promise<string> {
    try {
      const [colonyPDA] = this.getColonyPDA();
      const colony = (await this.program.account["colonyState"].fetch(
        colonyPDA,
      )) as ColonyState;

      const [fromAgentPDA] = this.getAgentPDA(colonyPDA, fromAgentIndex);
      const [toAgentPDA] = this.getAgentPDA(colonyPDA, toAgentIndex);
      const [vaultFromPDA] = this.getVaultPDA(fromAgentPDA);
      const [vaultToPDA] = this.getVaultPDA(toAgentPDA);

      // Derive TransactionLog PDA using the current total_transactions counter.
      const [logPDA] = PublicKey.findProgramAddressSync(
        [
          Buffer.from("log"),
          colonyPDA.toBytes(),
          Buffer.from(colony.totalTransactions.toArray("le", 8)),
        ],
        this.programId,
      );

      const taskIdBytes = taskIdToBytes(taskId);

      const sig = await this.program.methods
        .agentPay(new BN(amount), taskIdBytes)
        .accounts({
          authority: this.wallet.publicKey,
          colony: colonyPDA,
          fromAgent: fromAgentPDA,
          vaultFrom: vaultFromPDA,
          toAgent: toAgentPDA,
          vaultTo: vaultToPDA,
          transactionLog: logPDA,
          systemProgram: SystemProgram.programId,
        })
        .signers([this.wallet])
        .rpc({ skipPreflight: false, commitment: "confirmed" });

      console.log(
        chalk.green(
          `[COLONY][${timestamp()}] agentPay ${fromAgentIndex}→${toAgentIndex} | ${amount} lamports | tx: ${sig}`,
        ),
      );
      return sig;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      throw new Error(
        `[ColonyClient.agentPay] Failed to send transaction: ${msg}`,
      );
    }
  }

  /**
   * Reports a task outcome for an agent via the `report_outcome` instruction.
   *
   * @param agentIndex - Zero-based index of the agent.
   * @param success    - `true` for success (+5 rep); `false` for failure (−10 rep).
   * @returns Transaction signature.
   * @throws `Error` if the transaction fails.
   */
  async reportOutcome(agentIndex: number, success: boolean): Promise<string> {
    try {
      const [colonyPDA] = this.getColonyPDA();
      const [agentPDA] = this.getAgentPDA(colonyPDA, agentIndex);

      const sig = await this.program.methods
        .reportOutcome(success)
        .accounts({
          authority: this.wallet.publicKey,
          colony: colonyPDA,
          agent: agentPDA,
        })
        .signers([this.wallet])
        .rpc({ skipPreflight: false, commitment: "confirmed" });

      console.log(
        chalk.green(
          `[COLONY][${timestamp()}] reportOutcome agent=${agentIndex} success=${success} tx: ${sig}`,
        ),
      );
      return sig;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      throw new Error(`[ColonyClient.reportOutcome] Failed: ${msg}`);
    }
  }

  /**
   * Freezes or unfreezes an agent via the `emergency_freeze` instruction.
   *
   * @param agentIndex - Zero-based index of the target agent.
   * @param freeze     - `true` to freeze; `false` to unfreeze.
   * @returns Transaction signature.
   * @throws `Error` if the transaction fails.
   */
  async emergencyFreeze(agentIndex: number, freeze: boolean): Promise<string> {
    try {
      const [colonyPDA] = this.getColonyPDA();
      const [agentPDA] = this.getAgentPDA(colonyPDA, agentIndex);

      const sig = await this.program.methods
        .emergencyFreeze(freeze)
        .accounts({
          authority: this.wallet.publicKey,
          colony: colonyPDA,
          agent: agentPDA,
        })
        .signers([this.wallet])
        .rpc({ skipPreflight: false, commitment: "confirmed" });

      console.log(
        chalk.green(
          `[COLONY][${timestamp()}] emergencyFreeze agent=${agentIndex} freeze=${freeze} tx: ${sig}`,
        ),
      );
      return sig;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      throw new Error(`[ColonyClient.emergencyFreeze] Failed: ${msg}`);
    }
  }

  // ───────────────────────────────────────────────────────────────────────────
  // Fetch helpers
  // ───────────────────────────────────────────────────────────────────────────

  /**
   * Fetches and returns the on-chain `ColonyState`.
   *
   * @returns `ColonyState` account data.
   * @throws `Error` if the account does not exist or fetch fails.
   */
  async fetchColonyState(): Promise<ColonyState> {
    const [colonyPDA] = this.getColonyPDA();
    const data = await this.program.account["colonyState"].fetch(colonyPDA);
    return data as ColonyState;
  }

  /**
   * Fetches and returns the on-chain `AgentState` for a given agent index.
   *
   * @param agentIndex - Zero-based agent index.
   * @returns `AgentState` account data.
   * @throws `Error` if the account does not exist or fetch fails.
   */
  async fetchAgentState(agentIndex: number): Promise<AgentState> {
    const [colonyPDA] = this.getColonyPDA();
    const [agentPDA] = this.getAgentPDA(colonyPDA, agentIndex);
    const data = await this.program.account["agentState"].fetch(agentPDA);
    return data as AgentState;
  }

  /**
   * Fetches and returns `AgentState` for all registered agents.
   *
   * @returns Array of `AgentState` objects (ordered by agent index).
   * @throws `Error` if the colony state or any agent account fetch fails.
   */
  async fetchAllAgentStates(): Promise<AgentState[]> {
    const colony = await this.fetchColonyState();
    const promises: Promise<AgentState>[] = [];
    for (let i = 0; i < colony.agentCount; i++) {
      promises.push(this.fetchAgentState(i));
    }
    return Promise.all(promises);
  }
}
